spring:
  config:
    import:
      - classpath:application-db.yml
  application:
    name: ticketing
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[default_schema]': public
server:
  port: 8088
logging:
  level:
    root: DEBUG