spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  config:
    import:
      - classpath:application-db.yml
  application:
    name: ticketing
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[default_schema]': public
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
server:
  port: 8088
logging:
  level:
    root: DEBUG
jwt:
  header: Authorization
  secret: 444b5a80712142b2a0b0a2f9f1e09f9f4af7c116cdb04c685d25230b1e8a307e9320b7269b5b32f19b5a98e298399969d25c61e1feec16e0f4e332b33ff93bd6
  token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

kospi:
  baseUrl:
    prfplc: http://kopis.or.kr/openApi/restful/prfplc
  serviceKey: e91a9f48e68e47ffaccbf3a10fc81a94